selected_scheme scheme-small
binary_x86_64-linux 1
collection-fontutils 1
collection-latex 1
option_adjustrepo 1
option_doc 1
option_fmt 1
option_letter 0
option_path 0
option_src 1
option_sys_bin /usr/local/bin
option_sys_info /usr/local/share/info
option_sys_man /usr/local/share/man
portable 0
